### ISSUE TITLE
This is not last.fm art fetcher

### ISSUE THREAD

**Issue by FDiskas** [friaca/art-fetcher#2]
Under the hood it uses spotify
https://github.com/lacymorrow/album-art/blob/2de1532b008004d426dcb9e7f9980f263697b9a6/index.js#L61

**Comment by friaca** [comment]
Yeah, they changed it. When I first made this, they used the Last.FM API instead of Spotify, I will stop using that package and rewrite the code.

**Comment by FDiskas** [comment]
Just letting you know that last.fm provides url to pictures but they are empty. According to they terms it can't be used else where. So instead if you try use it it will display sheriff star instead ⭐

**Comment by friaca** [comment]
Damn, that sucks... I'll have to decide what I'll do with this project then 🥴 Thanks for the heads up! :)
